'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui=Object.fromEntries(['score','hearts','dash','pause','overlay','title','message','play'].map(id=>[id,document.getElementById(id)]));
const W=960,H=540,home={x:110,y:275},keys=new Set();
let state='intro',bunny,carrots,foxes,particles,score,health,cooldown,burst,invulnerable,time,last=0,target=null;
const decorations=Array.from({length:135},(_,i)=>({x:(i*137.5+39)%W,y:(i*83.7+25)%H,s:i%4}));
function reset(){bunny={x:110,y:300,dx:1,dy:0};score=0;health=3;cooldown=burst=invulnerable=time=0;particles=[];carrots=Array.from({length:12},(_,i)=>({x:245+(i%4)*174+Math.sin(i*8)*32,y:100+Math.floor(i/4)*165+Math.cos(i*5)*22,taken:false}));foxes=[{x:850,y:130,phase:0},{x:760,y:420,phase:3},{x:520,y:270,phase:5}];target=null;keys.clear();state='playing';ui.overlay.hidden=true;ui.pause.textContent='Pause';sync();}
function sync(){ui.score.textContent=`${score} / 12`;ui.hearts.textContent='♥ '.repeat(health)+'♡ '.repeat(3-health);ui.dash.textContent=cooldown>0?`${cooldown.toFixed(1)}s`:'Ready';}
function modal(title,message,label){ui.title.textContent=title;ui.message.textContent=message;ui.play.textContent=label;ui.overlay.hidden=false;}
function pause(){if(state==='playing'){state='paused';keys.clear();target=null;modal('A moment in the meadow.','Your carrots can wait. Take a breath, little bunny.','Keep hopping →');ui.pause.textContent='Resume';}else if(state==='paused'){state='playing';ui.overlay.hidden=true;ui.pause.textContent='Pause';}}
function dash(){if(state==='playing'&&cooldown<=0){burst=.19;cooldown=2.2;}}
ui.play.onclick=()=>state==='paused'?pause():reset();ui.pause.onclick=pause;document.querySelector('#touchDash').onclick=dash;
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat&&e.code==='Space')dash();if(!e.repeat&&e.code==='KeyP')pause();});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(state==='playing')pause();});
function point(e){const r=canvas.getBoundingClientRect();target={x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
canvas.addEventListener('pointerdown',e=>{if(state==='playing'){canvas.setPointerCapture(e.pointerId);point(e);}});canvas.addEventListener('pointermove',e=>{if(canvas.hasPointerCapture(e.pointerId))point(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>target=null);
function puff(x,y,color){for(let i=0;i<10;i++)particles.push({x,y,vx:Math.cos(i)*65,vy:Math.sin(i)*65,life:.55,color});}
function update(dt){time+=dt;cooldown=Math.max(0,cooldown-dt);burst=Math.max(0,burst-dt);invulnerable=Math.max(0,invulnerable-dt);let dx=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),dy=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'));if(!dx&&!dy&&target){dx=target.x-bunny.x;dy=target.y-bunny.y;if(Math.hypot(dx,dy)<7)dx=dy=0;}const length=Math.hypot(dx,dy);if(length){bunny.dx=dx/length;bunny.dy=dy/length;}if(length||burst>0){const speed=burst>0?610:190;bunny.x=Math.max(24,Math.min(W-24,bunny.x+bunny.dx*speed*dt));bunny.y=Math.max(35,Math.min(H-24,bunny.y+bunny.dy*speed*dt));}
for(const c of carrots)if(!c.taken&&Math.hypot(c.x-bunny.x,c.y-bunny.y)<26){c.taken=true;score++;puff(c.x,c.y,'#ffce74');}
for(const f of foxes){let fx=bunny.x-f.x,fy=bunny.y-f.y;const distance=Math.hypot(fx,fy);if(distance>240||Math.hypot(bunny.x-home.x,bunny.y-home.y)<85){fx=Math.cos(time*.65+f.phase);fy=Math.sin(time*.9+f.phase);}const norm=Math.hypot(fx,fy)||1;f.x=Math.max(205,Math.min(W-25,f.x+fx/norm*78*dt));f.y=Math.max(40,Math.min(H-30,f.y+fy/norm*78*dt));if(distance<30&&invulnerable<=0&&burst<=0){health--;invulnerable=1.8;puff(bunny.x,bunny.y,'#fffaf0');if(health===0){state='lost';modal('A little rest, then retry.','Those foxes are quick! Dash past them with Space, and recover near your burrow.','Try again →');break;}}}
particles=particles.filter(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;return p.life>0;});if(state==='playing'&&score===12&&Math.hypot(bunny.x-home.x,bunny.y-home.y)<62){state='won';modal('Home, sweet burrow!','Twelve crunchy carrots and one happy bunny. The meadow is a little sweeter with you in it.','Play again →');}sync();}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function animal(x,y,fox=false){ctx.save();ctx.translate(x,y);ellipse(0,15,20,7,'#425b3825');if(fox){ctx.fillStyle='#c9733c';ctx.beginPath();ctx.moveTo(-17,-9);ctx.lineTo(-15,-29);ctx.lineTo(-3,-17);ctx.lineTo(12,-28);ctx.lineTo(18,-6);ctx.closePath();ctx.fill();ellipse(0,0,19,19,'#df8b4c');ellipse(0,8,12,10,'#ffe9c6');ellipse(-7,-1,2,2,'#3d4934');ellipse(7,-1,2,2,'#3d4934');ellipse(0,7,3,2,'#3d4934');}else{ellipse(-8,-23,6,20,'#fffaf0');ellipse(8,-25,6,21,'#fffaf0');ellipse(-8,-25,2.5,13,'#e8b3a6');ellipse(8,-27,2.5,14,'#e8b3a6');ellipse(0,3,18,19,'#fffaf0');ellipse(-11,17,7,4,'#fffaf0');ellipse(11,17,7,4,'#fffaf0');ellipse(-6,-1,2,2.5,'#3d4934');ellipse(6,-1,2,2.5,'#3d4934');ellipse(0,5,2.5,2,'#db9f98');ellipse(-11,5,3,2,'#efc9b9');ellipse(11,5,3,2,'#efc9b9');}ctx.restore();}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#bed593';ctx.fillRect(0,0,W,H);ellipse(540,280,440,225,'#c7db9f');ctx.strokeStyle='#d7dfab';ctx.lineWidth=66;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(110,290);ctx.bezierCurveTo(370,470,480,140,850,240);ctx.stroke();for(const d of decorations){if(d.s===0){ellipse(d.x,d.y,3,3,'#fff8d8');ellipse(d.x+4,d.y+2,3,3,'#fff8d8');ellipse(d.x+2,d.y+1,1.5,1.5,'#e3b95e');}else{ctx.strokeStyle='#94b67570';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(d.x-3,d.y-5);ctx.lineTo(d.x,d.y);ctx.lineTo(d.x+4,d.y-6);ctx.stroke();}}
ellipse(105,286,78,63,'#a5bf78');ellipse(105,280,50,42,'#728d52');ellipse(105,291,32,29,'#526943');ellipse(105,310,39,9,'#dec59a');ctx.fillStyle='#fff9e7';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(score===12?'COME HOME!':'COZY BURROW',105,222);
for(const c of carrots||[]){if(c.taken)continue;ctx.save();ctx.translate(c.x,c.y+Math.sin(time*3+c.x)*3);ctx.rotate(.3);ctx.fillStyle='#e99146';ctx.beginPath();ctx.moveTo(-7,-7);ctx.quadraticCurveTo(-9,1,0,16);ctx.quadraticCurveTo(10,0,7,-7);ctx.closePath();ctx.fill();ctx.strokeStyle='#648344';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-5,-16);ctx.moveTo(0,-6);ctx.lineTo(4,-18);ctx.stroke();ctx.restore();}
for(const f of foxes||[])animal(f.x,f.y,true);if(bunny){ctx.globalAlpha=invulnerable>0&&Math.sin(time*30)>0?.4:1;animal(bunny.x,bunny.y);ctx.globalAlpha=1;}for(const p of particles||[])ellipse(p.x,p.y,3,3,p.color);if(state==='playing'){ctx.fillStyle='#395736';ctx.font='13px system-ui';ctx.fillText(score===12?'Your basket is full. Head back to the burrow!':'Collect carrots • Dodge foxes • Find your way home',W/2,H-17);}}
function frame(now){const dt=Math.min((now-last)/1000,.033);last=now;if(state==='playing')update(dt);draw();requestAnimationFrame(frame);}reset();state='intro';modal('Hello, little hopper.','Gather 12 carrots for your cozy burrow. Watch out for the foxes, and use a quick dash when they get close!',"Let's hop →");requestAnimationFrame(frame);
